CREATE TABLE PRODUCT_DISCOUNTS
(
    PRODUCT_ID          BIGINT PRIMARY KEY,
    APPLY_EVERY_NTH     INT NOT NULL DEFAULT 1,
    FIXED_DISCOUNT      NUMERIC(20, 4),
    PERCENTAGE_DISCOUNT NUMERIC(5, 4),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS
);

INSERT INTO PRODUCT_DISCOUNTS VALUES(1, 1, null, 0.15);
